services:
  - type: web
    name: task-annotation-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
